### ISSUE TITLE
Issue with date/time formatting

### ISSUE THREAD

**Issue by DanBeast1337** [FunOrange/circle-tracker#1]
I am in Germany and when it sends the score to spreadsheets, the date and time format is incorrect.

I guess it has to do with the 
Line 387 in Tracker.cs -  `string dateTimeFormat = "g";`

I guess if just using one single Format, it could be fixed.
`string dateTimeFormat = "yyyy'-'MM'-'dd h':'mm tt";` 
That is the original Format, which it works with. 

I am no pro when it comes to coding and compiling, so I hope you can get it fixed.

![image](https://user-images.githubusercontent.com/9980963/86452111-25da0300-bd1c-11ea-9a9d-bed40c8c8946.png)

**Comment by FunOrange** [comment]
Very good catch. I fixed it. Thanks!!

**Comment by DanBeast1337** [comment]
It may have fixed it just half-way. Though the code should be correct, the "tt" at the End of the DateTimeFormat doesn't resolve in it saying and/or sending AM/PM Info, thus not filling it out in the Raw Data sheet. 

It may be a locale-related issue, I don't know if you can fix it with some code. 

![image](https://user-images.githubusercontent.com/9980963/86542965-99e1fa00-bf1a-11ea-85d2-689886f75971.png)
![image](https://user-images.githubusercontent.com/9980963/86542987-c72ea800-bf1a-11ea-8c7e-463e2f9d1177.png)
