### ISSUE TITLE
Star diff not working for non-english language 

### ISSUE THREAD

**Issue by YO7O** [FunOrange/circle-tracker#11]
when you are using non-english system, star diff doesn't works for some map
to be exact, this:
https://media.discordapp.net/attachments/731700986875215903/736190980075814952/unknown.png

for me, chinese & japanese doesn't work
maps before 23rd July are played on chinese
https://docs.google.com/spreadsheets/d/1rzPryBPTptEV_9a05AAB8y-_max7Z_GsGMn9rZoy5UU/edit#gid=771301926

**Comment by FunOrange** [comment]
Fixed
