### ISSUE TITLE
Not counting retries

### ISSUE THREAD

**Issue by Rhepsilon** [FunOrange/circle-tracker#3]
The tracker doesn't look like it's keeping track of retries. Not too sure if it's on purpose or not, but maybe add an option to track them.

**Comment by FunOrange** [comment]
It actually does track retries. The number of hits carries over to the next retry. I'll admit this behaviour is pretty weird and instead it should post a new entry every time you hit retry.

**Comment by Rhepsilon** [comment]
If that's the case, do you think you can add something where it counts the number of retries in the spread sheet?
