### ISSUE TITLE
Stats don't properly reset from Singleplayer to Multiplayer

### ISSUE THREAD

**Issue by chezbananas** [FunOrange/circle-tracker#7]
When playing a map with mods in singleplayer and then switching mods in a multiplayer lobby, the mods from singleplayer are still attached to each map.
![image](https://user-images.githubusercontent.com/5007763/88144720-3b6d7a80-cbae-11ea-8a9b-e45edd38c45f.png)
also the map that didn't record properly is [Tokyo Jihen - Sounan](https://osu.ppy.sh/beatmapsets/967321#osu/2031053)

didn't realize this at first but map stats also did not update properly (CS, AR, and OD are still fixed to Maze of Vapor)
![image](https://user-images.githubusercontent.com/5007763/88214060-6982a700-cc0e-11ea-91ba-09bb6ca40e69.png)

**Comment by FunOrange** [comment]
fixed
